apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: webcrawler-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          value: mongodb://mongodb:27017/crawler
        - name: NODE_ENV
          value: "development"
        command: ["node", "index.js"]
      volumes:
      - name: app-volume
        hostPath:
          path: /Users/kailloux/Desktop/projet_crawler
          type: Directory 