apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcrawler-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcrawler-api
  template:
    metadata:
      labels:
        app: webcrawler-api
    spec:
      containers:
      - name: webcrawler-api
        image: webcrawler-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcrawler-crawler1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcrawler-crawler1
  template:
    metadata:
      labels:
        app: webcrawler-crawler1
    spec:
      containers:
      - name: webcrawler-crawler1
        image: webcrawler-api:latest
        imagePullPolicy: Never
        command: ["node", "crawler1.js"]
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcrawler-crawler2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcrawler-crawler2
  template:
    metadata:
      labels:
        app: webcrawler-crawler2
    spec:
      containers:
      - name: webcrawler-crawler2
        image: webcrawler-api:latest
        imagePullPolicy: Never
        command: ["node", "crawler2.js"]
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: webcrawler-service
spec:
  selector:
    app: webcrawler-api
  ports:
  - port: 3001
    targetPort: 3001
  type: LoadBalancer 